# Generated by Django 5.0.7 on 2024-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians_directory_app', '0002_alter_albummodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
