# Generated by Django 5.0.7 on 2024-07-31 19:10

import django.db.models.deletion
import modelForm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=255)),
                ('date_field', models.DateField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_field', models.EmailField(max_length=254)),
                ('url_field', models.URLField()),
                ('time_field', models.TimeField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('json_field', models.JSONField()),
                ('integer_field', models.IntegerField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Medium2',
            fields=[
                ('big_auto_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('binary_field', models.BinaryField()),
                ('comma_separated_field', models.CharField(max_length=255, validators=[modelForm.models.comma_separated_validator])),
                ('date_time_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('file_field', models.FileField(upload_to='upload/')),
                ('file_path_field', models.FilePathField(path='upload/')),
                ('uuid_field', models.UUIDField()),
                ('text_field', models.TextField()),
                ('float_field', models.FloatField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('image_field', models.ImageField(upload_to='upload/')),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelForm.medium')),
            ],
        ),
    ]
